#!/bin/sh
#
# - yuriy.ilnytsky@datarobot.com
#
##### #### #### #### #### #### #### ####
ERROR () {
	echo
	echo "# ERROR."
	echo "$@"
	echo
	exit 1
}

#### #### #### #### #### #### #### ####
SYSTEM_OUTPUT=''
SYSTEM_ERROR=''
SYSTEM_EXITCODE=0
SYSTEM () {
	local OUT=''
	local COMMAND=''
	local IGNORE_ERRORS=false
	SYSTEM_OUTPUT=''
	SYSTEM_ERROR=''
	SYSTEM_EXITCODE=0
	while [ -n "$1" ]; do
		echo "$1"|egrep -i '^-*ignore-*errors*.*|^-ignore' >/dev/null && IGNORE_ERRORS=true || COMMAND="${COMMAND} ${1}"
		shift
	done; COMMAND=${COMMAND/ /}
	[ -z "${COMMAND}" ] && ERROR "function SYSTEM received no data to execute"
	if ! OUT=$(/bin/sh -c "${COMMAND}" 2>&1); then
		SYSTEM_EXITCODE=$?
		SYSTEM_ERROR="${OUT}"
		${IGNORE_ERRORS} && return 1
		echo "${OUT}"
		ERROR "Failed command: ${COMMAND}"
	fi
	SYSTEM_OUTPUT="${OUT}"
	return 0
}

#### #### #### #### #### #### #### ####
sudo_check () {
	sudo -n id|grep '^uid=0(root)' &>/dev/null ||
	ERROR "no sudo permissions granted '${DRUSER} ALL=(ALL) NOPASSWD: ALL'"
}

#### #### #### #### #### #### #### ####
wait_for_container () {
	local CC="$1"
	echo "|   |-- Datarobot container ${CC} status:"
	SYSTEM "docker ps"
	echo "${SYSTEM_OUTPUT}"|grep "\s${CC}$" >/dev/null || ERROR "Cannot find container ${CC} started"
	while echo "${SYSTEM_OUTPUT}"|grep "\s${CC}$"|grep  "starting" >/dev/null; do
		echo "|   |   |-- ${CC}: "$(echo "${SYSTEM_OUTPUT}"|grep "\s${CC}$"|sed "s/.*Up\s*/Up /g;s/\s*${CC}$//g"|xargs)
		sleep 40;
		SYSTEM "docker ps"
	done
	echo "|   |   '-- DataRobot container ${CC} is up and running"
}

#### #### #### #### #### #### #### ####
#### #### #### #### #### #### #### ####
SSH="ssh -t -q -o StrictHostKeyChecking=no -o BatchMode=yes"
MIGR_DIR="/opt/datarobot/data/backup"
MIGR_DIR_TO_CREATE="
	${MIGR_DIR}
	${MIGR_DIR}/secrets
	${MIGR_DIR}/secrets/certs
	${MIGR_DIR}/mongo
	${MIGR_DIR}/redis
	${MIGR_DIR}/pgsql
"
DRAPP_DIR_TO_CHECK="
	./certs
"
DR_APP_FILES_TO_CHECK="
	./bin/datarobot
	./config.yaml
"
DATA="/opt/datarobot/data"
DATE=$(date +%F)
BACKUP_DIR="/opt/datarobot/data/backups"
BACKUP_DIR_TO_CREATE="
	${BACKUP_DIR}/mongo
	${BACKUP_DIR}/pgsql
	${BACKUP_DIR}/redis
"
DRAPP_OBJECTS_TO_BACKUP="
	./certs
	./secrets
	./.secrets-key
	./secrets.yaml
	./config.yaml
	/etc/docker/daemon.json
	/opt/datarobot/etc
"

#### #### #### #### #### #### #### ####
dr_check () {
	sudo_check
	for i in ${BACKUP_DIR_TO_CREATE} ; do
		[ -d "${i}" ] || mkdir -p "${i}"
		[ -d "${i}" ] || ERROR "Cannot create ${MIGR_DIR}"
		#echo "|-- directory ${i}: Ok"
	done
}

#### #### #### #### #### #### #### ####
drapp_check () {
	dr_check
	for i in ${DRAPP_DIR_TO_CHECK} ; do
		[ -d "${i}" ] || ERROR "Directory not found: ${i}"
		#echo "|-- directory ${i}: Ok"
	done
	for i in ${DR_APP_FILES_TO_CHECK} ; do
		[ -f ${i} ] || ERROR "File not found: ${i}"
		#echo "|-- file ${i}: Ok"
	done
	for i in ${MIGR_DIR_TO_CREATE} ; do
		[ -d "${i}" ] || mkdir -p "${i}"
		[ -d "${i}" ] || ERROR "Cannot create ${MIGR_DIR}"
		#echo "|-- directory ${i}: Ok"
	done
}

#### #### #### #### #### #### #### ####
dr_stop () {
	echo "|-- Stopping DataRobot services..."
	SYSTEM "./bin/datarobot services stop"
	#echo "|"
	#echo "#### #### #### #### #### #### #### ####"
	#./bin/datarobot services stop || ERROR "Error stopping datarobot services"
	#echo "#### #### #### #### #### #### #### ####"
	#echo "|"
	#echo "|-- DataRobot services stopped"
}

#### #### #### #### #### #### #### ####
registry_start () {
	SYSTEM "docker start registry"
	echo "|-- DataRobot container registry started"
}

#### #### #### #### #### #### #### ####
registry_stop () {
	SYSTEM "docker stop registry" -ignore-errors
	echo "|-- DataRobot container registry stopped"
}

#### #### #### #### #### #### #### ####
drhelp () {
	echo
	echo "  Usage: $0 <ARG>"
	echo
	echo "On app server in DataRobot directory as datarobot user:"
	echo "  * list                  - on app to show list of all servers and services from config.yaml"
	echo "  * servers               - on app app check and list of servers/containers to back up"
	echo "  * backup-all            - to backup all from app"
	echo "    * backup-mongo        - to backup mongo DB from app"
	echo "    * backup-pgsql        - to backup mongo DB from app"
	echo "    * backup-redis        - to backup mongo DB from app"
	echo
	echo "On any datarobot server as datarobot user:"
	echo "  * check                 - on any to check current server sudo and backup directories"
	echo "  * backup-mongo-local    - to backup mongo DB on a local server"
	echo "  * backup-pgsql-local    - to backup pgsql DB on a local server"
	echo "  * backup-redis-local    - to backup redis DB on a local server"
	echo
	echo "Migration commands on app server in DataRobot directory as datarobot user:"
	echo "  * prepare-all            - to prepare  all backups ready for DataRobot9 on app node"
	echo "                             including secrets, MongoDB, PosgreSQL and Redis"
	echo "    * prepare-secrets        - to prepare secrets backup for DataRobot 9"
	echo "    * prepare-mongo          - to prepare MongoDB backup for DataRobot 9"
	echo "    * prepare-pgsql          - to prepare PostgreSQL backup for DataRobot 9"
	echo "    * prepare-redis          - to prepare Redis ready for DataRobot 9"
	echo
	exit 1
}

#### #### #### #### #### #### #### ####
declare -A SERVERS=()
servers_get () {
	local LIST=$(cat config.yaml|grep '^\s*-'|awk 'BEGIN{a=0;l=""}{if (/^\s*-\s*services:/){if(l!="")print l;l="";a=1}else{if(a==1){if(/^\s*-\s*[0-9]/){l=$2" "l}else{if(l==""){l=$2}else{l=l" "$2}}}}}END{print l}') || ERROR "Cannot parse config.yaml"
	echo "|-- DataRobot servers with services to backup:"
	for i in app mongo pgsql redis ; do
		echo "${LIST}"|egrep "\s${i}\s|\s${i}$" >/dev/null || ERROR "Cannot find ${i} container in config.yaml"
		local IP=$(echo "${LIST}"|egrep "\s${i}\s|\s${i}$"|awk '{print $1}'|head -1)
		[ -z "${IP}" ] && ERROR "Cannot determine ip for container ${i}"
		SERVERS[${i}]="${IP}"
		echo "|   |-- $i: ${SERVERS[${i}]}"
	done
	echo "|   '-- DataRobot servers with services to backup."
}

#### #### #### #### #### #### #### ####
backup_app () {
	drapp_check
	echo "|-- Objects to backup:"
	for i in ${DRAPP_OBJECTS_TO_BACKUP}; do
		[ ! -d ${i} ] && [ ! -f ${i} ] && ERROR "Not found: ${i}"
		SYSTEM "rsync -au ${i} ${BACKUP_DIR}/"
		echo "|   |-- ${i}: backed up"
	done
	echo "|   '-- Objects to backup: done"
}

#### #### #### #### #### #### #### ####
backup_redis_local () {
	dr_check
	for i in ${DATA} ${DATA}/redis ${BACKUP_DIR}/redis ; do
		[ -d "${i}" ] || ERROR "Directory not found: ${i}"
	done
	echo "|-- Backing up Redis on $(hostname -i)"
	SYSTEM "docker stop redis" -ignore-errors
	[ -f ${DATA}/redis/dump.rdb ] || ERROR "File not found: ${DATA}/redis/dump.rdb"
	echo "|   |-- File ${DATA}/redis/dump.rdb size $(ls -lah ${DATA}/redis/dump.rdb |awk '{print $5}')"
	SYSTEM "cp -f ${DATA}/redis/dump.rdb ${BACKUP_DIR}/redis/datarobot-redis-backup-${DATE}.rdb"
	echo "|   |-- ${BACKUP_DIR}/redis/datarobot-redis-backup-${DATE}.rdb size: $(ls -lah ${BACKUP_DIR}/redis/datarobot-redis-backup-${DATE}.rdb |awk '{print $5}')"
	echo "|   '-- Redis backed up on $(hostname -i)"
}

#### #### #### #### #### #### #### ####
backup_pgsql_local () {
	dr_check
	for i in ${DATA} ${DATA}/pgsql ${BACKUP_DIR}/pgsql ; do
		[ -d "${i}" ] || ERROR "Directory not found: ${i}"
	done
	echo "|-- Backing up PostgreSQL on $(hostname -i)"
	SYSTEM "docker start pgsql"
	wait_for_container "pgsql"
	[ -d "${DATA}/pgsql/backup" ] && ERROR "Directory exists ${DATA}/pgsql/backup, remove to continue"
	mkdir -p ${BACKUP_DIR}/pgsql/backup
	[ -d "${BACKUP_DIR}/pgsql/backup" ] || ERROR "Cannot create ${BACKUP_DIR}/pgsql/backup"
	echo "|   |-- Backing up PostgreSQL, ${DATA}/pgsql size: $(du -sh ${DATA}/pgsql|awk '{print $1}')..."
	SYSTEM "docker exec -i pgsql /entrypoint python -m tools.manager.pgsql create-backup --backup-location /opt/datarobot-runtime/data/postgresql/backup/"
	SYSTEM "docker stop pgsql"
	echo "|   |   |-- Creating tarball, backup size: $(du -sh ${DATA}/pgsql/backup|awk '{print $1}')..."
	SYSTEM "cd ${DATA}/pgsql && tar -cf ${BACKUP_DIR}/pgsql/datarobot-pgsql-backup-${DATE}.tar --remove-files backup"
	echo "|   |   '-- ${BACKUP_DIR}/pgsql/datarobot-pgsql-backup-${DATE}.tar size: $(ls -lah ${BACKUP_DIR}/pgsql/datarobot-pgsql-backup-${DATE}.tar |awk '{print $5}')"
	echo "|   '-- PostgreSQL backed up on $(hostname -i)"
}

#### #### #### #### #### #### #### ####
backup_mongo_local () {
	dr_check
	for i in ${DATA} ${DATA}/mongo ${BACKUP_DIR}/mongo ; do
		[ -d "${i}" ] || ERROR "Directory not found: ${i}"
	done
	echo "|-- Backing up MongoDB on $(hostname -i)"
	SYSTEM "docker start mongo"
	wait_for_container "mongo"
	[ -d "${DATA}/mongo/backup" ] && ERROR "Directory exists ${DATA}/mongo/backup, remove to continue"
	mkdir -p ${BACKUP_DIR}/mongo/backup
	[ -d "${BACKUP_DIR}/mongo/backup" ] || ERROR "Cannot create ${BACKUP_DIR}/mongo/backup"
	echo "|   |-- Backing up MongoDB, ${DATA}/mongo size: $(du -sh ${DATA}/mongo|awk '{print $1}')..."
	SYSTEM "docker exec -i mongo /entrypoint sbin/datarobot-manage-mongo backup --backup-dir /opt/datarobot-runtime/data/mongo/backup"
	SYSTEM "docker stop mongo"
	echo "|   |   |-- Creating tarball, backup size: $(du -sh ${DATA}/mongo/backup|awk '{print $1}')..."
	SYSTEM "cd ${DATA}/mongo && tar -cf ${BACKUP_DIR}/mongo/datarobot-mongo-backup-${DATE}.tar --remove-files backup"
	echo "|   |   '-- ${BACKUP_DIR}/mongo/datarobot-mongo-backup-${DATE}.tar size: $(ls -lah ${BACKUP_DIR}/mongo/datarobot-mongo-backup-${DATE}.tar |awk '{print $5}')"
	echo "|   '-- MongoDB backed up on $(hostname -i)"
}

#### #### #### #### #### #### #### ####
servers () {
	drapp_check
	servers_get
}

#### #### #### #### #### #### #### ####
backup_mongo () {
	servers
	dr_stop
	SYSTEM "${SSH} ${SERVERS[mongo]} 'hostname -i'"
	${SSH} ${SERVERS[mongo]} '/bin/sh -s' < $0 backup-mongo-local || ERROR "Failed backing up MongoDB"
}

#### #### #### #### #### #### #### ####
backup_pgsql () {
	servers
	dr_stop
	SYSTEM "${SSH} ${SERVERS[pgsql]} 'hostname -i'"
	${SSH} ${SERVERS[pgsql]} '/bin/sh -s' < $0 backup-pgsql-local || ERROR "Failed backing up PostgreSQL"
}

#### #### #### #### #### #### #### ####
backup_redis () {
	servers
	dr_stop
	SYSTEM "${SSH} ${SERVERS[redis]} 'hostname -i'"
	${SSH} ${SERVERS[redis]} '/bin/sh -s' < $0 backup-redis-local || ERROR "Failed backing up Redis"
}

#### #### #### #### #### #### #### ####
backup_all () {
	servers
	dr_stop
	backup_app
	SYSTEM "${SSH} ${SERVERS[mongo]} 'hostname -i'"
        #echo "'-- #### #### #### #### #### #### #### ####"
        ${SSH} ${SERVERS[mongo]} '/bin/sh -s' < $0 backup-mongo-local || ERROR "Failed backing up MongoDB"
	${SSH} ${SERVERS[pgsql]} '/bin/sh -s' < $0 backup-pgsql-local || ERROR "Failed backing up PostgreSQL"
	${SSH} ${SERVERS[redis]} '/bin/sh -s' < $0 backup-redis-local || ERROR "Failed backing up Redis"
	#echo ".-- #### #### #### #### #### #### #### ####"
}
#### #### #### #### #### #### #### ####
list () {
	drapp_check
	cat config.yaml|grep '^\s*-'|awk 'BEGIN{a=0;l=""}{if (/^\s*-\s*services:/){if(l!="")print l;l="";a=1}else{if(a==1){if(/^\s*-\s*[0-9]/){l=$2" "l}else{if(l==""){l=$2}else{l=l" "$2}}}}}END{print l}'
	exit 0
}

#### #### #### #### #### #### #### ####
#
# backup secrets
#
prepare_secrets () {
	drapp_check
	echo "|-- Backing up secrets"
	SYSTEM "docker start app"
	wait_for_container "app"
	SYSTEM "rsync -au ./config.yaml ${MIGR_DIR}/"
	echo "|   |-- config.yaml: Ok"
	[ -d ${MIGR_DIR}/secrets ] || mkdir -p ${MIGR_DIR}/secrets
	SYSTEM "rsync -au ./secrets.yaml ${MIGR_DIR}/secrets/"
	echo "|   |-- secrets.yaml: Ok"
	echo "|   |-- directory ./certs: Ok"
	SYSTEM "rsync -au --delete ./certs/ ${MIGR_DIR}/secrets/certs/"
	SYSTEM "docker exec -it app /entrypoint datarobot-manage-secrets read-secret ASYMMETRIC_KEY_PAIR_MONGO_ENCRYPTION_KEY"
	echo "${SYSTEM_OUTPUT}"|grep "^aesgcm256:" >/dev/null || ERROR "Cannot get ASYMMETRIC_KEY_PAIR_MONGO_ENCRYPTION_KEY"
	echo "${SYSTEM_OUTPUT}"|grep "^aesgcm256:" >${MIGR_DIR}/secrets/ASYMMETRIC_KEY_PAIR_MONGO_ENCRYPTION_KEY.txt
	echo "|   |-- ${MIGR_DIR}/secrets/ASYMMETRIC_KEY_PAIR_MONGO_ENCRYPTION_KEY.txt: Ok"
	SYSTEM "docker exec -it app /entrypoint datarobot-manage-secrets read-secret DRSECURE_MONGO_ENCRYPTION_KEY"
	echo "${SYSTEM_OUTPUT}"|grep "^aesgcm256:" >/dev/null || ERROR "Cannot get DRSECURE_MONGO_ENCRYPTION_KEY"
	echo "${SYSTEM_OUTPUT}"|grep "^aesgcm256:" >${MIGR_DIR}/secrets/DRSECURE_MONGO_ENCRYPTION_KEY.txt
	echo "|   |-- ${MIGR_DIR}/secrets/DRSECURE_MONGO_ENCRYPTION_KEY.txt: Ok"
	SYSTEM "docker stop app"
	echo "|   '-- Backing up secrets: Ok"
}

#### #### #### #### #### #### #### ####
#
# MongoDB migration 
#
prepare_mongo_local_pre () {
	dr_check
	for i in ${DATA} ${DATA}/mongo ${BACKUP_DIR}/mongo ; do
		[ -d "${i}" ] || ERROR "Directory not found: ${i}"
	done
	echo "|-- Migration MongoDB preparation on $(hostname -i)"
	[ -d "${DATA}/mongo/backup" ] && ERROR "Directory exists ${DATA}/mongo/backup, remove to continue"
	echo "|   |-- Backing up MongoDB, ${DATA}/mongo size: $(du -sh ${DATA}/mongo|awk '{print $1}')..."
	if [ -d ${DATA}/mongo_backup_42 ]; then
		echo "|   |-- Backup directory ${DATA}/mongo_backup_42 found"
		if diff -r ${DATA}/mongo ${DATA}/mongo_backup_42 >/dev/null; then
			echo "|   '-- mongo and mongo_backup_42 are identical"
		else
			echo "|   '-- mongo and mongo_backup_42 are NOT identical"
			ERROR "update backup manually or delete it (if deleted, the script will recreate it)"
		fi
	else
		mkdir -p ${DATA}/mongo_backup_42
		[ -d ${DATA}/mongo_backup_42 ] || ERROR "Cannot create ${DATA}/mongo_backup_42"
		echo "|   |-- backing up mongo to ${DATA}/mongo_backup_42 ..."
		SYSTEM "rsync -au --delete ${DATA}/mongo/ ${DATA}/mongo_backup_42/"
		echo "|   '-- ${DATA}/mongo_backup_42 backup created"
	fi
	mkdir -p ${DATA}/mongo/backup
	[ -d "${DATA}/mongo/backup" ] || ERROR "Cannot create ${DATA}/mongo/backup"
}

#### #### #### #### #### #### #### ####
prepare_mongo_datadump () {
	drapp_check
	registry_start
	echo "|-- ./bin/datarobot upgrade-mongo --mongo-upgrade-end=5.0 --backup-after-upgrade"
	echo "|   |-- MongoDB data size $(du -sh ${DATA}/mongo|awk '{print $1}')"
	echo "|   |   |-- ... wait ..."
	echo "|   |   |-- to check status: tail -f ./mongo5.log"
	./bin/datarobot upgrade-mongo --mongo-upgrade-end=5.0 --backup-after-upgrade-to=/opt/datarobot-runtime/data/mongo/backup &>./mongo5.log
	#echo "|"
	#echo "| #### #### #### #### #### #### #### ####"
	#./bin/datarobot upgrade-mongo --mongo-upgrade-end=5.0 --backup-after-upgrade-to=/opt/datarobot-runtime/data/mongo/backup || ERROR "Failed command: ./bin/datarobot upgrade-mongo --mongo-upgrade-end=5.0 --backup-after-upgrade-to=/opt/datarobot-runtime/data/mongo/backup"
	#echo "| #### #### #### #### #### #### #### ####"
	#echo "|   '-- Mongo DB upgraded from version 4.2 to version 5"
	echo 
	registry_stop
}

#### #### #### #### #### #### #### ####
prepare_mongo_local_post () {
	dr_check
	for i in ${DATA} ${DATA}/mongo ${BACKUP_DIR}/mongo ; do
		[ -d "${i}" ] || ERROR "Directory not found: ${i}"
	done
	[ -d ${DATA}/mongo/backup ] || ERROR "Directory ${DATA}/mongo/backup not found"
	echo "|-- Migration MongoDB 5 backup on $(hostname -i)"
	echo "|   |-- Creating tarball, backup size: $(du -sh ${DATA}/mongo/backup|awk '{print $1}')..."
	SYSTEM "cd ${DATA}/mongo && tar -cf ${BACKUP_DIR}/mongo/datarobot-mongo50-backup-${DATE}.tar --remove-files backup"
	echo "|   |-- ${BACKUP_DIR}/mongo/datarobot-mongo50-backup-${DATE}.tar size: $(ls -lah ${BACKUP_DIR}/mongo/datarobot-mongo50-backup-${DATE}.tar |awk '{print $5}')"
	echo "|   '-- Migration MongoDB 5 backup created"
	#
	[ -d ${DATA}/mongo_backup_42 ] || ERROR "Directory ${DATA}/mongo_backup_42 to restore Mongo version 4.2 data is missing"
	#
	[ -d ${DATA}/mongo_backup_50 ] && SYSTEM "rm -rf ${DATA}/mongo_backup_50"
	SYSTEM "mv ${DATA}/mongo ${DATA}/mongo_backup_50"
	echo "|-- MongoDB 5 data stored in ${DATA}/mongo_backup_50/"
	#SYSTEM "mkdir -p ${DATA}/mongo; chmod 0755 ${DATA}/mongo"
	#SYSTEM "rsync -au --delete ${DATA}/mongo_backup_42/ ${DATA}/mongo/"
	SYSTEM "mv ${DATA}/mongo_backup_42 ${DATA}/mongo"
	echo "|-- MongoDB version 4.2 data restored"
}
#### #### #### #### #### #### #### ####
prepare_mongo () {
	servers
        dr_stop
        SYSTEM "${SSH} ${SERVERS[mongo]} 'hostname -i'"
        ${SSH} ${SERVERS[mongo]} '/bin/sh -s' < $0 prepare-mongo-local-pre || ERROR "Failed prepare MongoDB migration"
	prepare_mongo_datadump
        ${SSH} ${SERVERS[mongo]} '/bin/sh -s' < $0 prepare-mongo-local-post || ERROR "Failed prepare MongoDB migration"
	SYSTEM "scp ${SERVERS[mongo]}:${BACKUP_DIR}/mongo/datarobot-mongo50-backup-${DATE}.tar ${MIGR_DIR}/mongo/"
	echo "|-- MongoDB 5 backup: ${MIGR_DIR}/mongo/datarobot-mongo50-backup-${DATE}.tar size $(ls -lah ${MIGR_DIR}/mongo/datarobot-mongo50-backup-${DATE}.tar |awk '{print $5}')"
}

#### #### #### #### #### #### #### ####
prepare_pgsql_local () {
	dr_check
	for i in ${DATA} ${DATA}/pgsql ${BACKUP_DIR}/pgsql ; do
		[ -d "${i}" ] || ERROR "Directory not found: ${i}"
	done
	echo "|-- Backing up PostgreSQL on $(hostname -i)"
	SYSTEM "docker start pgsql"
	wait_for_container "pgsql"
	SYSTEM "docker exec -i pgsql /entrypoint datarobot-manage-secrets read-secret PGSQL_POSTGRES_PASSWORD 2>/dev/null"
	#echo
	#echo "SYSTEM_OUTPUT=[${SYSTEM_OUTPUT}]"
	#echo
	local PGPASSWORD=$(echo "${SYSTEM_OUTPUT}"| tail -n1 | tr -d '\n\r')
	SYSTEM "docker exec -i pgsql /entrypoint bash -c \"export PGPASSWORD='${PGPASSWORD}'; psql -U postgres -h localhost -d modmon -c 'DROP EXTENSION timescaledb;'\"" -ignore-errors
	#
	# modmon sql backup
	####SYSTEM "docker exec -i pgsql /entrypoint bash -c \"export PGPASSWORD='${PGPASSWORD}'; pg_dump -U postgres -h localhost -d modmon --clean --create -f /opt/datarobot-runtime/data/postgresql/datarobot-pgsql-modmon-backup-${DATE}.sql\""
	####SYSTEM "mv -f ${DATA}/pgsql/datarobot-pgsql-modmon-backup-${DATE}.sql ${BACKUP_DIR}/pgsql/"
	#
	# modmon binary backup
	#SYSTEM "mkdir -p ${BACKUP_DIR}/pgsql/pgsql-${DATE}"
	#SYSTEM "docker exec -i pgsql /entrypoint bash -c 'mkdir -p /opt/datarobot-runtime/data/postgresql/pgsql-modmon'"
	[ -d "${DATA}/pgsql/backup" ] && ERROR "Directory exists ${DATA}/pgsql/backup, remove to continue"
	SYSTEM "mkdir -p /opt/datarobot/data/pgsql/backup"
	SYSTEM "docker exec -i pgsql /entrypoint bash -c \"export PGPASSWORD='${PGPASSWORD}'; pg_dump -U postgres -h localhost -Fd -j4 modmon -f /opt/datarobot-runtime/data/postgresql/backup/modmon\""
	SYSTEM "docker stop pgsql"
	SYSTEM "cd /opt/datarobot/data/pgsql/ && tar cf pgsql-modmon-${DATE}.tar backup"
	SYSTEM "mv /opt/datarobot/data/pgsql/pgsql-modmon-${DATE}.tar ${BACKUP_DIR}/pgsql/"
	SYSTEM "rm -rf /opt/datarobot/data/pgsql/backup"
	#
}

#### #### #### #### #### #### #### ####
prepare_pgsql () {
	servers
	dr_stop
	SYSTEM "${SSH} ${SERVERS[pgsql]} 'hostname -i'"
	${SSH} ${SERVERS[pgsql]} '/bin/sh -s' < $0 prepare-pgsql-local || ERROR "Failed prepare PostgreSQL migration"
	####SYSTEM "scp ${SERVERS[pgsql]}:${BACKUP_DIR}/pgsql/datarobot-pgsql-modmon-backup-${DATE}.sql ${MIGR_DIR}/pgsql/"
	####echo "|-- PostgreSQL backup: ${MIGR_DIR}/pgsql/datarobot-pgsql-modmon-backup-${DATE}.sql size $(ls -lah ${MIGR_DIR}/pgsql/datarobot-pgsql-modmon-backup-${DATE}.sql |awk '{print $5}')"
	SYSTEM "scp ${SERVERS[pgsql]}:${BACKUP_DIR}/pgsql/pgsql-modmon-${DATE}.tar ${MIGR_DIR}/pgsql/"
	echo "|-- PostgreSQL binary backup: ${MIGR_DIR}/pgsql/pgsql-modmon-${DATE}.tar size $(ls -lah ${MIGR_DIR}/pgsql/pgsql-modmon-${DATE}.tar |awk '{print $5}')"
}

#### #### #### #### #### #### #### ####
prepare_redis () {
	servers
	dr_stop
	SYSTEM "${SSH} ${SERVERS[redis]} 'hostname -i'"
	${SSH} ${SERVERS[redis]} '/bin/sh -s' < $0 backup-redis-local || ERROR "Failed backing up Redis"
	SYSTEM "scp ${SERVERS[redis]}:${BACKUP_DIR}/redis/datarobot-redis-backup-${DATE}.rdb ${MIGR_DIR}/redis/"
	echo "|-- Redis backup: ${MIGR_DIR}/redis/datarobot-redis-backup-${DATE}.rdb size $(ls -lah ${MIGR_DIR}/redis/datarobot-redis-backup-${DATE}.rdb |awk '{print $5}')"
}

#### #### #### #### #### #### #### ####
#### #### #### #### #### #### #### ####
prepare_all () {
	servers
        dr_stop
	#
	prepare_secrets
	#
	# mongo5
	#
        SYSTEM "${SSH} ${SERVERS[mongo]} 'hostname -i'"
        ${SSH} ${SERVERS[mongo]} '/bin/sh -s' < $0 prepare-mongo-local-pre || ERROR "Failed prepare MongoDB migration"
	prepare_mongo_datadump
        ${SSH} ${SERVERS[mongo]} '/bin/sh -s' < $0 prepare-mongo-local-post || ERROR "Failed prepare MongoDB migration"
	SYSTEM "scp ${SERVERS[mongo]}:${BACKUP_DIR}/mongo/datarobot-mongo50-backup-${DATE}.tar ${MIGR_DIR}/mongo/"
	echo "|-- MongoDB 5 backup: ${MIGR_DIR}/mongo/datarobot-mongo50-backup-${DATE}.tar size $(ls -lah ${MIGR_DIR}/mongo/datarobot-mongo50-backup-${DATE}.tar |awk '{print $5}')"
	#
	# pgsql
	#
	SYSTEM "${SSH} ${SERVERS[pgsql]} 'hostname -i'"
	${SSH} ${SERVERS[pgsql]} '/bin/sh -s' < $0 prepare-pgsql-local || ERROR "Failed prepare PostgreSQL migration"
	####SYSTEM "scp ${SERVERS[pgsql]}:${BACKUP_DIR}/pgsql/datarobot-pgsql-modmon-backup-${DATE}.sql ${MIGR_DIR}/pgsql/"
	####echo "|-- PostgreSQL backup: ${MIGR_DIR}/pgsql/datarobot-pgsql-modmon-backup-${DATE}.sql size $(ls -lah ${MIGR_DIR}/pgsql/datarobot-pgsql-modmon-backup-${DATE}.sql |awk '{print $5}')"
	SYSTEM "scp ${SERVERS[pgsql]}:${BACKUP_DIR}/pgsql/pgsql-modmon-${DATE}.tar ${MIGR_DIR}/pgsql/"
	echo "|-- PostgreSQL binary backup: ${MIGR_DIR}/pgsql/pgsql-modmon-${DATE}.tar size $(ls -lah ${MIGR_DIR}/pgsql/pgsql-modmon-${DATE}.tar |awk '{print $5}')"
	#
	# redis
	#
        SYSTEM "${SSH} ${SERVERS[redis]} 'hostname -i'"
        ${SSH} ${SERVERS[redis]} '/bin/sh -s' < $0 backup-redis-local || ERROR "Failed backing up Redis"
	SYSTEM "scp ${SERVERS[redis]}:${BACKUP_DIR}/redis/datarobot-redis-backup-${DATE}.rdb ${MIGR_DIR}/redis/"
	echo "|-- Redis backup: ${MIGR_DIR}/redis/datarobot-redis-backup-${DATE}.rdb size $(ls -lah ${MIGR_DIR}/redis/datarobot-redis-backup-${DATE}.rdb |awk '{print $5}')"
	#
}


#### #### #### #### #### #### #### ####
#### #### #### #### #### #### #### ####
#### MAIN PROGRAM
#### #### #### #### #### #### #### ####
#### #### #### #### #### #### #### ####
echo "$@"|tr 'A-Z' 'a-z'|egrep "^list$|^list\s|\slist\s|\slist$" >/dev/null && list
[ -z "$1" ] && drhelp
ACT0="$0"
ACTION="$0 $@"
[ "${ACT0}" = "/bin/sh" ] || echo ".-- Action: ${ACTION}"
while [ -n "$1" ]; do
	COMMAND=$(echo "$1"|tr 'A-Z' 'a-z')
	case ${COMMAND} in
		check) dr_check
			echo "|   |-- checks passed: Ok"
			;;
		list) list ;;
		servers) servers ;;
		backup-mongo-local) backup_mongo_local ;;
		backup-mongo) backup_mongo ;;
		backup-pgsql-local) backup_pgsql_local ;;
		backup-pgsql) backup_pgsql ;;
		backup-redis-local) backup_redis_local ;;
		backup-redis) backup_redis ;;
		backup-app) backup_app ;;
		backup-all) backup_all ;;
		prepare-secrets) prepare_secrets ;;
		prepare-mongo-local-pre) prepare_mongo_local_pre ;;
		prepare-mongo-datadump) prepare_mongo_datadump ;;
		prepare-mongo-local-post) prepare_mongo_local_post ;;
		prepare-mongo) prepare_mongo ;;
		prepare-pgsql-local) prepare_pgsql_local ;;
		prepare-pgsql) prepare_pgsql ;;
		prepare-redis) prepare_redis ;;
		prepare-all) prepare_all ;;
		*) drhelp
			ERROR "Wrong arguments" ;;
	esac
	shift
done
[ "${ACT0}" = "/bin/sh" ] || echo "'-- Action: ${ACTION}"
#### #### #### #### #### #### #### ####
#### #### #### #### #### #### #### ####

